name: Release
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install -g pnpm && pnpm install
      
      - name: Full Test Suite
        run: pnpm run test:all
        
      - name: Publish to NPM
        run: pnpm publish --filter @hydra-lens/core
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - name: Package Extension for Chrome Store
        run: cd packages/extension/dist && zip -r extension.zip .
        
      - name: Package CLI via pkg
        run: pnpm run build:binaries
        
      - name: GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            packages/extension/dist/extension.zip
            packages/cli/dist/hydra-lens-win.exe
            packages/cli/dist/hydra-lens-mac
            packages/cli/dist/hydra-lens-linux
